packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - expo-document-picker@57.0.1
  - '@expo/env@2.4.2'
  - '@expo/image-utils@0.11.3'
  - '@expo/require-utils@57.0.3'
  - expo-application@57.0.1
  - expo-constants@57.0.5
  - expo-notifications@57.0.5

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
