import type { WidgetSize, WidgetType } from "@portfolio/shared";
import {
  ALL_SIZES,
  youtubeEmbedDefault,
  youtubeEmbedLabel,
  youtubeEmbedSchema,
  techStackDefault,
  techStackLabel,
  techStackSchema,
  paypalDefault,
  paypalLabel,
  paypalSchema,
  letterboxdDefault,
  letterboxdLabel,
  letterboxdSchema,
  toileDefault,
  toileLabel,
  toileSchema,
  lolDefault,
  lolLabel,
  lolSchema,
  videoDefault,
  videoLabel,
  videoSchema,
  countdownDefault,
  countdownLabel,
  countdownSchema,
  freeLinkDefault,
  freeLinkLabel,
  freeLinkSchema,
  githubStatsDefault,
  githubStatsLabel,
  githubStatsSchema,
  guestbookDefault,
  guestbookLabel,
  guestbookSchema,
  locationMapDefault,
  locationMapLabel,
  locationMapSchema,
  noteDefault,
  noteLabel,
  noteSchema,
  nowPlayingDefault,
  nowPlayingLabel,
  nowPlayingSchema,
  photoDefault,
  photoLabel,
  photoSchema,
  pollDefault,
  pollLabel,
  pollSchema,
  socialLinkDefault,
  socialLinkLabel,
  socialLinkSchema,
  spotifyEmbedDefault,
  spotifyEmbedLabel,
  spotifyEmbedSchema,
  statusDefault,
  statusLabel,
  statusSchema,
  visitorCounterDefault,
  visitorCounterLabel,
  visitorCounterSchema,
  watchlistDefault,
  watchlistLabel,
  watchlistSchema,
  weatherDefault,
  weatherLabel,
  weatherSchema,
} from "@portfolio/shared";
import type { ZodTypeAny } from "zod";

// Mobile widget registry. Reuses the SHARED per-type Zod schemas, defaults and
// labels (single source of truth with the web app). The sizes / descriptions
// / emoji mirror the web registry (apps/web/src/widgets/registry.ts); keep the
// two in sync when a widget type's declared sizes change.

const s = (w: number, h: number): WidgetSize => ({ w, h });

export type MobileWidgetMeta = {
  schema: ZodTypeAny;
  defaultConfig: unknown;
  label: string;
  description: string;
  emoji: string;
  sizes: readonly WidgetSize[];
  // Starting size for a fresh widget (defaults to sizes[0] if omitted).
  defaultSize: WidgetSize;
};

// Phase 4.5: every type offers the 9 universal sizes; `defaultSize` is the
// sensible starting size for a fresh widget. Mirrors apps/web/src/widgets/registry.ts.
export const registry: Record<WidgetType, MobileWidgetMeta> = {
  "social-link": {
    schema: socialLinkSchema,
    defaultConfig: socialLinkDefault,
    label: socialLinkLabel,
    description: "Lien vers un réseau social.",
    emoji: "🔗",
    sizes: ALL_SIZES,
    defaultSize: s(1, 1),
  },
  note: {
    schema: noteSchema,
    defaultConfig: noteDefault,
    label: noteLabel,
    description: "Un mot libre, style post-it.",
    emoji: "📝",
    sizes: ALL_SIZES,
    defaultSize: s(2, 2),
  },
  "location-map": {
    schema: locationMapSchema,
    defaultConfig: locationMapDefault,
    label: locationMapLabel,
    description: "Carte de ta ville.",
    emoji: "📍",
    sizes: ALL_SIZES,
    defaultSize: s(2, 2),
  },
  guestbook: {
    schema: guestbookSchema,
    defaultConfig: guestbookDefault,
    label: guestbookLabel,
    description: "Les visiteurs laissent un mot.",
    emoji: "💌",
    sizes: ALL_SIZES,
    defaultSize: s(3, 2),
  },
  "spotify-embed": {
    schema: spotifyEmbedSchema,
    defaultConfig: spotifyEmbedDefault,
    label: spotifyEmbedLabel,
    description: "Playlist ou album Spotify.",
    emoji: "🎧",
    sizes: ALL_SIZES,
    defaultSize: s(2, 2),
  },
  "spotify-now-playing": {
    schema: nowPlayingSchema,
    defaultConfig: nowPlayingDefault,
    label: nowPlayingLabel,
    description: "Le titre en cours d'écoute.",
    emoji: "🎵",
    sizes: ALL_SIZES,
    defaultSize: s(2, 1),
  },
  photo: {
    schema: photoSchema,
    defaultConfig: photoDefault,
    label: photoLabel,
    description: "Une photo ou un mini-carrousel.",
    emoji: "🖼️",
    sizes: ALL_SIZES,
    defaultSize: s(2, 2),
  },
  video: {
    schema: videoSchema,
    defaultConfig: videoDefault,
    label: videoLabel,
    description: "Une vidéo en lecture auto, muette et en boucle.",
    emoji: "🎞️",
    sizes: ALL_SIZES,
    defaultSize: s(2, 2),
  },
  "github-stats": {
    schema: githubStatsSchema,
    defaultConfig: githubStatsDefault,
    label: githubStatsLabel,
    description: "Graphe de contributions GitHub.",
    emoji: "🐙",
    sizes: ALL_SIZES,
    defaultSize: s(3, 2),
  },
  status: {
    schema: statusSchema,
    defaultConfig: statusDefault,
    label: statusLabel,
    description: "Ton statut / humeur du moment.",
    emoji: "💬",
    sizes: ALL_SIZES,
    defaultSize: s(2, 1),
  },
  weather: {
    schema: weatherSchema,
    defaultConfig: weatherDefault,
    label: weatherLabel,
    description: "Météo locale (Open-Meteo).",
    emoji: "⛅",
    sizes: ALL_SIZES,
    defaultSize: s(1, 1),
  },
  countdown: {
    schema: countdownSchema,
    defaultConfig: countdownDefault,
    label: countdownLabel,
    description: "Compte à rebours vers une date.",
    emoji: "⏳",
    sizes: ALL_SIZES,
    defaultSize: s(1, 1),
  },
  watchlist: {
    schema: watchlistSchema,
    defaultConfig: watchlistDefault,
    label: watchlistLabel,
    description: "Films / séries en cours.",
    emoji: "🎬",
    sizes: ALL_SIZES,
    defaultSize: s(2, 2),
  },
  "visitor-counter": {
    schema: visitorCounterSchema,
    defaultConfig: visitorCounterDefault,
    label: visitorCounterLabel,
    description: "Compteur de visites (live).",
    emoji: "👀",
    sizes: ALL_SIZES,
    defaultSize: s(1, 1),
  },
  poll: {
    schema: pollSchema,
    defaultConfig: pollDefault,
    label: pollLabel,
    description: "Un sondage, les visiteurs votent.",
    emoji: "📊",
    sizes: ALL_SIZES,
    defaultSize: s(2, 2),
  },
  "free-link": {
    schema: freeLinkSchema,
    defaultConfig: freeLinkDefault,
    label: freeLinkLabel,
    description: "N'importe quelle URL.",
    emoji: "✨",
    sizes: ALL_SIZES,
    defaultSize: s(2, 1),
  },
  "youtube-embed": {
    schema: youtubeEmbedSchema,
    defaultConfig: youtubeEmbedDefault,
    label: youtubeEmbedLabel,
    description: "Une vidéo YouTube intégrée.",
    emoji: "▶️",
    sizes: ALL_SIZES,
    defaultSize: s(2, 2),
  },
  "tech-stack": {
    schema: techStackSchema,
    defaultConfig: techStackDefault,
    label: techStackLabel,
    description: "Grille de badges de tes technos.",
    emoji: "🧩",
    sizes: ALL_SIZES,
    defaultSize: s(3, 2),
  },
  paypal: {
    schema: paypalSchema,
    defaultConfig: paypalDefault,
    label: paypalLabel,
    description: "Tuile de don paypal.me, sobre.",
    emoji: "☕",
    sizes: ALL_SIZES,
    defaultSize: s(2, 1),
  },
  letterboxd: {
    schema: letterboxdSchema,
    defaultConfig: letterboxdDefault,
    label: letterboxdLabel,
    description: "Tes 4 derniers films (Letterboxd).",
    emoji: "🎞️",
    sizes: ALL_SIZES,
    defaultSize: s(2, 3),
  },
  toile: {
    schema: toileSchema,
    defaultConfig: toileDefault,
    label: toileLabel,
    description: "Toile collaborative : les visiteurs dessinent.",
    emoji: "🎨",
    sizes: ALL_SIZES,
    defaultSize: s(2, 2),
  },
  lol: {
    schema: lolSchema,
    defaultConfig: lolDefault,
    label: lolLabel,
    description: "Ton rang ou ton champion favori (LoL).",
    emoji: "🎮",
    sizes: ALL_SIZES,
    defaultSize: s(2, 1),
  },
};

export function meta(type: WidgetType): MobileWidgetMeta {
  return registry[type];
}

export const ALL_TYPES = Object.keys(registry) as WidgetType[];
