-- ============================================================
-- Phase 8 — Multiple dashboard versions (/qrcode/[slug]).
-- Adds a `dashboards` table; every widget and every site_settings row is
-- attached to one dashboard version. The printed-QR default version keeps
-- slug 'default' and can never be deleted nor renamed. Admin presence
-- (tz/lat/lng/city) stays GLOBAL — it lives on the default version's row.
-- Idempotent: safe to run multiple times in the Supabase SQL editor.
-- Run after 0006_presence_status.sql.
-- ============================================================

-- ---------- dashboards -----------------------------------------------------
create table if not exists public.dashboards (
  id         uuid primary key default gen_random_uuid(),
  slug       text not null unique,
  name       text not null default '',
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);

-- Exactly one default version.
create unique index if not exists dashboards_single_default
  on public.dashboards (is_default) where is_default;

-- Seed the default version (the one behind the printed QR codes).
insert into public.dashboards (slug, name, is_default)
values ('default', 'Version par défaut', true)
on conflict (slug) do nothing;

-- The default version cannot be deleted, renamed (slug), or un-defaulted.
create or replace function public.protect_default_dashboard()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'DELETE' then
    if old.is_default then
      raise exception 'Cannot delete the default dashboard';
    end if;
    return old;
  end if;
  -- UPDATE
  if old.is_default and new.slug <> old.slug then
    raise exception 'Cannot rename the default dashboard slug';
  end if;
  if old.is_default and not new.is_default then
    raise exception 'Cannot unset the default dashboard';
  end if;
  return new;
end;
$$;

drop trigger if exists protect_default_dashboard on public.dashboards;
create trigger protect_default_dashboard
  before update or delete on public.dashboards
  for each row execute function public.protect_default_dashboard();

-- ---------- widgets.dashboard_id -------------------------------------------
alter table public.widgets
  add column if not exists dashboard_id uuid references public.dashboards (id) on delete cascade;

-- Backfill existing widgets onto the default version, then require it.
update public.widgets
   set dashboard_id = (select id from public.dashboards where is_default limit 1)
 where dashboard_id is null;

alter table public.widgets alter column dashboard_id set not null;

create index if not exists widgets_dashboard_idx on public.widgets (dashboard_id);

-- ---------- site_settings per version --------------------------------------
-- The header (name/tagline/status/chips) is per version. The single-row design
-- (id = 1) becomes one row per dashboard, keyed by dashboard_id.

-- Drop the "id = 1" single-row check (name is auto-generated by Postgres).
do $$
declare c text;
begin
  select conname into c
    from pg_constraint
   where conrelid = 'public.site_settings'::regclass
     and contype = 'c'
     and pg_get_constraintdef(oid) ilike '%id = 1%';
  if c is not null then
    execute format('alter table public.site_settings drop constraint %I', c);
  end if;
end $$;

-- Sequence-backed id so new versions get a fresh row id.
create sequence if not exists public.site_settings_id_seq owned by public.site_settings.id;
select setval(
  'public.site_settings_id_seq',
  greatest((select coalesce(max(id), 1) from public.site_settings), 1)
);
alter table public.site_settings alter column id set default nextval('public.site_settings_id_seq');

alter table public.site_settings
  add column if not exists dashboard_id uuid references public.dashboards (id) on delete cascade;

update public.site_settings
   set dashboard_id = (select id from public.dashboards where is_default limit 1)
 where dashboard_id is null;

create unique index if not exists site_settings_dashboard_id_key
  on public.site_settings (dashboard_id);

-- ---------- realtime -------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'dashboards'
  ) then
    alter publication supabase_realtime add table public.dashboards;
  end if;
end $$;

-- ---------- RLS ------------------------------------------------------------
alter table public.dashboards enable row level security;

drop policy if exists "dashboards public read"  on public.dashboards;
drop policy if exists "dashboards admin insert"  on public.dashboards;
drop policy if exists "dashboards admin update"  on public.dashboards;
drop policy if exists "dashboards admin delete"  on public.dashboards;

-- Everyone can read the version list (public pages resolve a slug).
create policy "dashboards public read" on public.dashboards
  for select to anon, authenticated using (true);

-- Only the admin manages versions.
create policy "dashboards admin insert" on public.dashboards
  for insert to authenticated with check (true);
create policy "dashboards admin update" on public.dashboards
  for update to authenticated using (true) with check (true);
create policy "dashboards admin delete" on public.dashboards
  for delete to authenticated using (true);
